services:

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://aryapathak22:00601221@cluster0.vnck4ub.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

